version: '3.8'

services:
  app:
    build: .
    container_name: mi_aplicacion
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/predictions_db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: mi_base_de_datos
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: predictions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
